### PR TITLE
Fixing SQL driver out of date error

### PR DESCRIPTION
**Pull request by Geph**
Attempted to fix this:
```
15.10 14:02:20 [Server] ERROR ] com.mysql.jdbc.Driver Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```
But I am not very smart so I don't know if I did it right.

### CODE REVIEW

**Comment by jackah2** [comment]
Check out how this was previously fixed https://github.com/whimc/Observations/pull/29/files

**Comment by Geph** [comment]
Mimicked what Jack did on WHIMC observations, essentially removing the driver call and having it ignore the error, I think.

**Comment by jackah2** [comment]
> Mimicked what Jack did on WHIMC observations, essentially removing the driver call and having it ignore the error, I think.

The catch statement is separate from the warning we were getting and is for attempting to connect to get a database connecting. Older versions of Java require manually loading the MySQL driver but it is now done automatically (that's why we were getting the warning).

Can you confirm these changes fix the warning? If so, this looks good.

**Comment by Geph** [comment]
I didn't realize there had been so many version updates since 2.0.5? Anyway loaded it on the beta server and appears to be working fine there without errors.

**Review by jackah2 — APPROVED** [review]

**Pull request merged**
